config/routes.rb
Rails.application.routes.draw do
  resources :administradors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
  resources :articles do
    resources :comments
  end
  resources :tags

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  
end

app/models/administrador.rb
class Administrador < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

    def tag_list
        self.tags.collect do |tag|
            tag.name
        end.join(", ")
    end

    def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
        self.tags = new_or_found_tags
    #validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

    end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :article
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/administradors_controller.rb
class AdministradorsController < ApplicationController
  before_action :zero_authors_or_authenticated, only: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  # GET /administradors or /administradors.json
  def index
    @administradors = Administrador.all
  end

  # GET /administradors/1 or /administradors/1.json
  def show
  end

  # GET /administradors/new
  def new
    @administrador = Administrador.new
  end

  # GET /administradors/1/edit
  def edit
  end

  # POST /administradors or /administradors.json
  def create
    @administrador = Administrador.new(administrador_params)

    respond_to do |format|
      if @administrador.save
        format.html { redirect_to administrador_url(@administrador), notice: "Administrador was successfully created." }
        format.json { render :show, status: :created, location: @administrador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administradors/1 or /administradors/1.json
  def update
    respond_to do |format|
      if @administrador.update(administrador_params)
        format.html { redirect_to administrador_url(@administrador), notice: "Administrador was successfully updated." }
        format.json { render :show, status: :ok, location: @administrador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administradors/1 or /administradors/1.json
  def destroy
    @administrador.destroy

    respond_to do |format|
      format.html { redirect_to administradors_url, notice: "Administrador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrador
      @administrador = Administrador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def administrador_params
      params.require(:administrador).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    def  index
        @articles = Article.all
    end

    def show

        @article = Article.find(params[:id])
        @comment = Comment.new
        @comment.article_id = @article.id
        
    end

    def new
        @article = Article.new
    end

    def create
        # esta es una forma de hacerlo
        #    @article = Article.new(
        #       title: params[:article][:title],
        #       body: params[:article][:body])
        #segunda fomra
        @article = Article.new(article_params)
        @article.save

        flash.notice = "Created '#{@article.title}' Successfull!"

        redirect_to root_path
    end

    def destroy

        @article = Article.destroy(params[:id])

        flash.notice = "Article '#{@article.title}' Deleted!"

        redirect_to article_path
    end

    def edit
        @article = Article.find(params[:id])

    end

    def update
        @article = Article.find(params[:id])
        @article.update(article_params)

        flash.notice = "Article '#{@article.title}' Update!"
      
        redirect_to article_path(@article)
    end

    def article_params
        params.require(:article).permit(:title, :body, :tag_list, :image)
    end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
    def new
    end
  
    def create
      if login(params[:email], params[:password])
        redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
      else
        flash.now.alert = "Login failed."
        render action: :new
      end
    end
  
    def destroy
      logout
      redirect_to(:administradors, notice: 'Logged out!')
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment = Comment.new(comment_params)
        @comment.article_id = params[:article_id]
      
        @comment.save
      
        redirect_to article_path(@comment.article)
      end
      
      def comment_params
        params.require(:comment).permit(:author_name, :body)
      end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def show
        @tag = Tag.find(params[:id])
    end
    def  index
        @tags = Tag.all
    end
end

app/helpers/administradors_helper.rb
module AdministradorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def article_params
        params.require(:article).permit(:title, :body, :tag_list, :image)
    end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/administradors/_administrador.html.erb
<div id="<%= dom_id administrador %>">
  <p>
    <strong>Username:</strong>
    <%= administrador.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= administrador.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= administrador.password %>
  </p>

  <p>
    <strong>Password confirmation:</strong>
    <%= administrador.password_confirmation %>
  </p>

</div>

app/views/administradors/_form.html.erb
<%= form_with(model: administrador) do |form| %>
  <% if administrador.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(administrador.errors.count, "error") %> prohibited this administrador from being saved:</h2>

      <ul>
        <% administrador.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/administradors/edit.html.erb
<h1>Editing administrador</h1>

<%= render "form", administrador: @administrador %>

<br>

<div>
  <%= link_to "Show this administrador", @administrador %> |
  <%= link_to "Back to administradors", administradors_path %>
</div>

app/views/administradors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Administradors</h1>

<div id="administradors">
  <% @administradors.each do |administrador| %>
    <%= render administrador %>
    <p>
      <%= link_to "Show this administrador", administrador %>
    </p>
  <% end %>
</div>

<%= link_to "New administrador", new_administrador_path %>

app/views/administradors/new.html.erb
<h1>New administrador</h1>

<%= render "form", administrador: @administrador %>

<br>

<div>
  <%= link_to "Back to administradors", administradors_path %>
</div>

app/views/administradors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @administrador %>

<div>
  <%= link_to "Edit this administrador", edit_administrador_path(@administrador) %> |
  <%= link_to "Back to administradors", administradors_path %>

  <%= button_to "Destroy this administrador", @administrador, method: :delete %>
</div>

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  
  <p class="comment"><%= comment.body %>
  
  <% if comment.created_at != nil  %>  
    <footer class="comment">Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</footer>
  <% end %>

  </p>

</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
  <%= f.label :tag_list %><br />
  <%= f.text_field :tag_list %>
</p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  
<p>
  <% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
  <% end %>
  <%= f.label :image, "Attach a New Image" %><br />
  <%= f.file_field :image %>
</p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
        
        <%= link_to article.title, article_path(article), class: 'article_title', id: "article_#{article.id}" %>

    </li>
  <% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, class: "new_article" %>
<%= link_to "All Tags", tags_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>Crear un nuevo artículo</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<p><%= image_tag @article.image.url %>

</p>
<p><%= @article.body %></p>
<div>
<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments.reverse %>
</div>
<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Articles List", articles_path %>

<%=  link_to "delete", article_path(@article), data: {turbo_method: :delete, confirm: "Really delete the article?"} %>

<%= link_to "edit", edit_article_path(@article) %>

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/comments/_form.html.erb
<div>
    <h3>Post a Comment</h3>
    <p>
        <%= form_for [ @article, @comment ] do |f| %>
        <p>
            <%= f.label :author_name, "Your Name"  %>
            <br/>
            <%= f.text_field :author_name %>
        </p>
        <p>
            <%= f.label :body %><br/>
            <%= f.text_area :body %>
        </p>
        <p>
            <%= f.submit 'Submit' %>
        </p>
        <% end %>
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="flash">
      <%= flash.notice %>
    </p>
  <div id="container">
    <div id="content">
      <%= yield %>
      <hr>
      <h6>
        <% if logged_in? %>
          <%= "Logged in as #{current_user.email}" %>
          <%= link_to "(logout)", logout_path %>
        <% else %>
          <%= link_to "(login)", login_path %>
        <% end %>
      </h6>
    </div>
  </div>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All tags</h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
        
        <%= link_to tag.name, tag_path(tag), class: 'article_title' %>

    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>